#!/usr/bin/perl -w
#                              -*- Mode: Perl -*-
# server.pl ---
# Author           : Manoj Srivastava ( srivasta@ember.green-gryphon.com )
# Created On       : Wed Apr  2 08:01:59 2003
# Created On Node  : ember.green-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Fri Apr  9 14:19:39 2004
# Last Machine Used: glaurung.internal.golden-gryphon.com
# Update Count     : 57
# Status           : Unknown, Use with caution!
# HISTORY          :
# Description      :
#
#

use strict;
require 5.002;
use Getopt::Long;
use Data::Dumper;
use Pod::Usage;

BEGIN {
  ($main::MYNAME     = $main::0) =~ s|.*/||;
  $main::Author      = "Manoj Srivastava";
  $main::AuthorMail  = "manoj.srivastava\@stdc.com";
  $main::Version     = (qw$Revision: 1.7 $ )[-1];
  $main::Version_ID  = q$Id: cnccalc,v 1.7 2003/12/16 01:33:47 srivasta Exp $;
}

use CnCCalc;
use Log::Log4perl qw(:levels);
use CnCCalc::Server;
use CnCCalc::Server::Welcome;
use CnCCalc::Server::Status;
use CnCCalc::Server::New_DataBase;
use CnCCalc::Server::Admin;
use CnCCalc::Server::Analysis;
use CnCCalc::Server::Create;
use CnCCalc::Server::New_Runs;
use CnCCalc::Server::Detailed_Status;
use CnCCalc::Server::New_Baseline;
use CnCCalc::Server::Create_Baseline;
use CnCCalc::Server::New_Stress;
use CnCCalc::Server::Create_Stressed;
use CnCCalc::Server::Analyze;
use CnCCalc::Server::Create_Results;
use CnCCalc::Server::Show_Results;
use CnCCalc::Server::Delete_Runs;
use CnCCalc::Server::Script_Baseline;
use CnCCalc::Server::Script_Stressed;
use CnCCalc::Server::Script_Results;
use CnCCalc::Server::Script_Report_Mop;
use CnCCalc::Server::Script_Initialize;

sub main {
  my $optdesc  = CnCCalc->Optdesc();
  my $defaults = CnCCalc->Defaults();

  Getopt::Long::Configure ("bundling_override", "permute");
  GetOptions (%$optdesc) or print "\n", CnCCalc->Usage();
  pod2usage(-exitstatus => 0, -verbose => 2) if $::ConfOpts{'man'};

  if (defined $::ConfOpts{'logconf'} && $::ConfOpts{'logconf'} &&
      -r $::ConfOpts{'logconf'}) {
    if (defined $::ConfOpts{'logwait'} && $::ConfOpts{'logwait'}){
      Log::Log4perl->init_and_watch($::ConfOpts{'logconf'}, $::ConfOpts{'logwait'});
    }
    else {
      Log::Log4perl->init($::ConfOpts{'logconf'});
    }
  }
  else {
    my $cnccalc_logger = get_logger("CnCCalc");
    $cnccalc_logger->level($INFO); 

    my $layout = Log::Log4perl::Layout::PatternLayout->new("%d{ISO8601} (%l)>%n\t%c %m%n");

    # Define an appender
    my $appender = Log::Log4perl::Appender->new("Log::Log4perl::Appender::Screen",
						name => 'Dump_TTY');

    # Set the appender's layout
    $appender->layout($layout);
    $cnccalc_logger->add_appender($appender);

    my $logfile;
    if (defined $::ConfOpts{'logfile'} && $::ConfOpts{'logfile'}) {
      $logfile = Log::Log4perl::Appender->new("Log::Log4perl::Appender::File",
					      name     => 'Dump_file',
					      min_level => 'debug',
					      filename  => "$::ConfOpts{'logfile'}",
					      mode      => 'append');
      $logfile->layout($layout);
      $cnccalc_logger->add_appender($$logfile);
    }
  }


  my $calc = CnCCalc->new(%::ConfOpts);
  $calc->validate(%::ConfOpts) unless 
    defined $::ConfOpts{'Config_File'} && -r $::ConfOpts{'Config_File'};
  my $confref = $calc->get_config_ref();


  # start a server
  CnCCalc::Server::Welcome::register();
  CnCCalc::Server::Status::register();
  CnCCalc::Server::New_DataBase::register();
  CnCCalc::Server::Admin::register();
  CnCCalc::Server::Analysis::register();
  CnCCalc::Server::Create::register();
  CnCCalc::Server::New_Runs::register();
  CnCCalc::Server::Detailed_Status::register();
  CnCCalc::Server::New_Baseline::register();
  CnCCalc::Server::Create_Baseline::register();
  CnCCalc::Server::New_Stress::register();
  CnCCalc::Server::Create_Stressed::register();
  CnCCalc::Server::Analyze::register();
  CnCCalc::Server::Create_Results::register();
  CnCCalc::Server::Show_Results::register();
  CnCCalc::Server::Delete_Runs::register();
  CnCCalc::Server::Script_Baseline::register();
  CnCCalc::Server::Script_Stressed::register();
  CnCCalc::Server::Script_Results::register();
  CnCCalc::Server::Script_Report_Mop::register();
  CnCCalc::Server::Script_Initialize::register();

  CnCCalc::Server::server_start('Configuration' => $calc);
  print "$main::Version_ID. done\n";
}

&main();

exit 0;

__END__
